on: ["push", "pull_request"]

name: Test Codecov with Workspace

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        repository: biothings/bte-trapi-workspace

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install, generate coverage report
      run: |
        npm run clone
        npm i || true && npm i
        npm run test-cov --workspace=@biothings-explorer/call-apis

    - name: Send coverage report to codecov for visualization
      uses: codecov/codecov-action@v3
      with:
        working-directory: ./packages/@biothings-explorer/call-apis
        files: ./coverage/lcov.info
        verbose: true
